#[test]
fn lcm_engine_switch_cancels_candidates_and_rolling_api_fails_closed() -> Result<()> {
    let mut session = make_lcm_session("lcm_engine_switch", 20);
    let mut manager = CompactionManager::new().with_budget(1_000);
    manager.engine = crate::config::CompactionEngine::Lcm;
    for _ in 0..20 {
        manager.notify_message_added();
    }
    assert!(
        manager
            .force_compact_with(
                &session.messages_for_provider_uncached(),
                Arc::new(MockSummaryProvider),
            )
            .is_err(),
        "rolling API must fail closed while LCM owns context"
    );
    let source = manager.capture_lcm_source(
        &session,
        10,
        "model".into(),
        "provider".into(),
        "route".into(),
        None,
        850,
        "reactive".into(),
    )?;
    manager.prepared_lcm_context = Some(CompactionManager::prepare_lcm_context(
        source,
        CompactionResult {
            summary_text: "must be cancelled".into(),
            atomic_parent_summaries: Vec::new(),
            openai_encrypted_content: None,
            covers_up_to_turn: 10,
            duration_ms: 1,
            summarized_messages: 10,
        },
    )?);

    assert!(manager.synchronize_engine(crate::config::CompactionEngine::Rolling));
    assert!(!manager.is_compacting());
    let (materialized, event) = manager.materialize_lcm_context(&mut session)?;
    assert_eq!(materialized.len(), session.messages.len());
    assert!(event.is_none());
    assert!(session.context_nodes.is_empty());
    Ok(())
}

#[test]
fn lcm_engine_switch_rebuilds_from_raw_after_encrypted_native_state() {
    let persisted = crate::session::StoredCompactionState {
        summary_text: String::new(),
        openai_encrypted_content: Some("opaque-native-state".to_string()),
        covers_up_to_turn: 12,
        original_turn_count: 20,
        compacted_count: 12,
    };
    let mut manager = CompactionManager::new();
    manager.engine = crate::config::CompactionEngine::Rolling;
    manager.restore_persisted_state(&persisted, 20);
    assert_eq!(manager.compacted_count, 12);
    assert!(manager.active_summary.is_some());

    assert!(manager.synchronize_engine(crate::config::CompactionEngine::Lcm));
    assert_eq!(manager.compacted_count, 0);
    assert!(manager.active_summary.is_none());
    assert!(manager.active_chars.is_dirty());

    let mut restarted_lcm = CompactionManager::new();
    restarted_lcm.engine = crate::config::CompactionEngine::Lcm;
    restarted_lcm.restore_persisted_state(&persisted, 20);
    assert_eq!(restarted_lcm.compacted_count, 0);
    assert!(restarted_lcm.active_summary.is_none());
    assert!(restarted_lcm.active_chars.is_dirty());
    assert!(!restarted_lcm.synchronize_engine(crate::config::CompactionEngine::Lcm));
}

#[test]
fn lcm_legacy_fallback_rejects_iterative_owned_projection() -> Result<()> {
    let mut session = make_lcm_session("lcm_iterative_legacy_rejection", 20);
    session.compaction = Some(crate::session::StoredCompactionState {
        summary_text: "already generated by LCM".to_string(),
        openai_encrypted_content: None,
        covers_up_to_turn: 10,
        original_turn_count: 10,
        compacted_count: 10,
    });
    let mut manager = CompactionManager::new();
    manager.engine = crate::config::CompactionEngine::Lcm;
    manager.compacted_count = 10;
    assert_eq!(
        manager.install_critical_legacy_summary(&mut session, 15)?,
        None
    );
    assert!(session.context_nodes.is_empty());
    Ok(())
}

#[test]
fn lcm_route_policy_preserves_exact_identity_and_rejects_live_route_change() -> Result<()> {
    let mut session = make_lcm_session("lcm_route_policy", 20);
    session.model = Some("nvidia/example".into());
    session.provider_key = Some("openai-compatible:nvidia-nim".into());
    session.route_api_method = Some("openai-compatible:nvidia-nim".into());
    assert_eq!(
        lcm_route_spec(&session, "fallback", None),
        "nvidia-nim:nvidia/example"
    );
    assert_eq!(
        lcm_route_spec(&session, "fallback", Some("claude-api:claude-fable-5")),
        "claude-api:claude-fable-5"
    );

    let mut manager = CompactionManager::new();
    manager.engine = crate::config::CompactionEngine::Lcm;
    let source = manager.capture_lcm_source(
        &session,
        10,
        "nvidia/example".into(),
        "openai-compatible".into(),
        "nvidia-nim:nvidia/example".into(),
        None,
        850,
        "reactive".into(),
    )?;
    let mut policy = crate::config::CompactionConfig {
        engine: crate::config::CompactionEngine::Lcm,
        ..Default::default()
    };
    assert!(source.matches_runtime_policy(&session, &policy));

    session.route_api_method = Some("openai-api-key".into());
    session.provider_key = Some("openai".into());
    assert!(!source.matches_runtime_policy(&session, &policy));
    policy.model = Some("claude-api:claude-fable-5".into());
    assert!(!source.matches_runtime_policy(&session, &policy));

    session.model = Some("active-model".into());
    session.provider_key = Some("openai".into());
    session.route_api_method = Some("openai-api-key".into());
    let active_fallback = manager.capture_lcm_source(
        &session,
        10,
        "active-model".into(),
        "openai".into(),
        "openai-api:active-model".into(),
        Some("selected-model".into()),
        850,
        "critical_active_route".into(),
    )?;
    policy.model = Some("selected-model".into());
    assert!(active_fallback.matches_runtime_policy(&session, &policy));
    policy.model = Some("new-selected-model".into());
    assert!(!active_fallback.matches_runtime_policy(&session, &policy));
    Ok(())
}

#[test]
fn lcm_inherited_route_uses_typed_runtime_identity_matrix() -> Result<()> {
    let mut session = make_lcm_session("lcm_typed_route", 20);
    session.model = Some("nvidia/example".into());
    session.provider_key = Some("openai-compatible:nvidia-nim".into());
    session.route_api_method = Some("openai-compatible:nvidia-nim".into());
    let profile = lcm_inherited_route_selection(&session, "fallback").unwrap();
    assert_eq!(
        profile.runtime_key,
        crate::provider::RuntimeKey::OpenAiCompatible {
            profile_id: Some("nvidia-nim".to_string())
        }
    );

    session.model = Some("openai/gpt-5@Fireworks".into());
    session.provider_key = Some("openrouter".into());
    session.route_api_method = Some("openrouter".into());
    let openrouter = lcm_inherited_route_selection(&session, "fallback").unwrap();
    assert_eq!(
        openrouter.runtime_key,
        crate::provider::RuntimeKey::OpenRouter
    );
    assert_eq!(openrouter.model, "openai/gpt-5");
    assert_eq!(openrouter.provider_label, "Fireworks");
    assert_eq!(
        crate::provider::persisted_session_model_for_route(&openrouter, "openai/gpt-5"),
        "openai/gpt-5@Fireworks"
    );
    assert_eq!(
        crate::provider::persisted_session_model_for_route(&profile, "nvidia/example"),
        "nvidia/example"
    );

    session.model = Some("gpt-5.4".into());
    session.provider_key = Some("openai-api-key".into());
    session.route_api_method = Some("openai-api-key".into());
    let openai = lcm_inherited_route_selection(&session, "fallback").unwrap();
    assert_eq!(
        openai.runtime_key,
        crate::provider::RuntimeKey::OpenAIApiKey
    );

    let selections = Arc::new(std::sync::Mutex::new(Vec::new()));
    let provider = RouteCapturingProvider {
        selections: Arc::clone(&selections),
    };
    set_lcm_inherited_route(&provider, &openai)?;
    assert_eq!(selections.lock().unwrap().as_slice(), &[openai]);
    Ok(())
}

#[test]
fn lcm_route_fingerprint_changes_after_auth_generation_change() {
    let session = make_lcm_session("lcm_auth_fingerprint", 20);
    let before = lcm_route_policy_fingerprint_with_auth_generation(&session, None, 41);
    let after = lcm_route_policy_fingerprint_with_auth_generation(&session, None, 42);
    assert_ne!(before, after);

    let account_one = lcm_route_policy_fingerprint_with_runtime_identity(
        &session,
        None,
        42,
        Some("claude-1"),
        Some("openai-1"),
    );
    let account_two = lcm_route_policy_fingerprint_with_runtime_identity(
        &session,
        None,
        42,
        Some("claude-1"),
        Some("openai-2"),
    );
    assert_ne!(account_one, account_two);
}

#[tokio::test]
async fn lcm_adapts_to_real_compactor_ceiling_without_dropping_source_coverage() -> Result<()> {
    let calls = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let provider: Arc<dyn Provider> = Arc::new(AdaptiveLimitProvider {
        calls: Arc::clone(&calls),
        max_prompt_chars: 2_500,
    });
    let planted_facts = [
        "the orchard is north",
        "the bakery opens early",
        "the cabin roof is green",
        "the delta route is closed",
        "the eagle nests nearby",
        "the fountain uses rainwater",
        "the garden gate is oak",
        "the harbor light is amber",
        "the island ferry runs daily",
        "the junction sign faces west",
    ];
    let messages = planted_facts
        .iter()
        .map(|fact| {
            make_text_message(
                Role::User,
                &format!("planted fact: {fact}. {}", "\nordinary chunk".repeat(80)),
            )
        })
        .collect::<Vec<_>>();

    let result = generate_lcm_compaction_artifact(
        provider,
        messages.clone(),
        None,
        None,
        LcmJobPriority::Background,
    )
    .await?;

    assert_eq!(result.summarized_messages, messages.len());
    assert!(!result.summary_text.is_empty());
    for fact in planted_facts {
        assert!(
            result
                .summary_text
                .contains(&format!("planted fact: {fact}.")),
            "adaptive retries must retain planted fact {fact}; summary={}",
            result.summary_text
        );
    }
    assert!(calls.load(std::sync::atomic::Ordering::SeqCst) >= 3);
    assert!(
        LCM_SAFE_PROMPT_CHARS
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner())
            .get("adaptive-limit:small-context")
            .copied()
            .is_some_and(|chars| chars <= 2_048)
    );
    Ok(())
}

#[test]
fn lcm_context_limit_classifier_accepts_common_provider_phrasing() {
    for message in [
        "context length exceeded",
        "too many tokens in request",
        "prompt is too long",
        "maximum token limit reached",
        "input is too long",
    ] {
        assert!(
            is_lcm_context_limit_error(&anyhow::anyhow!(message)),
            "missed {message}"
        );
    }
    assert!(!is_lcm_context_limit_error(&anyhow::anyhow!(
        "authentication failed"
    )));
}

#[test]
fn lcm_output_requires_exact_source_grounding_for_every_claim() {
    let source = "Do not claim all tests pass.\nObserved command failed.";
    assert!(!lcm_output_is_grounded(
        "- [source] The whole change set is now green and landed.",
        source
    ));
    assert!(!lcm_output_is_grounded(
        "- [source] All tests pass.",
        source
    ));
    assert!(!lcm_output_is_grounded(
        "# Everything is complete and credentials follow",
        source
    ));
    assert!(lcm_output_is_grounded(
        "- [source] Do not claim all tests pass.",
        source
    ));
    assert!(lcm_output_is_grounded("None observed.", source));
}

#[test]
fn lcm_grounding_repair_keeps_exact_excerpts_and_drops_unsupported_claims() {
    let source = "Do not claim all tests pass.\nObserved command failed.";
    let candidate = structured_test_summary(
        "Observed command failed.\nThe whole change set is now green and landed.",
    );

    let repaired =
        repair_lcm_output_grounding(&candidate, source, usize::MAX).expect("structured repair");

    assert!(repaired.contains("- [source] Observed command failed."));
    assert!(!repaired.contains("green and landed"));
    assert!(lcm_output_has_required_sections(&repaired));
    assert!(lcm_output_is_grounded(&repaired, source));
}

#[test]
fn lcm_grounding_repair_accepts_exact_contiguous_partial_line() {
    let source = "Observed command: cargo test -p jcode-base. Result: 36 passed.";
    let candidate = structured_test_summary("Result: 36 passed.");
    let repaired = repair_lcm_output_grounding(&candidate, source, 900)
        .expect("exact contiguous excerpt should survive repair");

    assert!(
        repaired
            .contains("- [source] Observed command: cargo test -p jcode-base. Result: 36 passed.")
    );
    assert!(lcm_output_is_grounded(&repaired, source));
}

#[test]
fn lcm_deterministic_reduction_preserves_chunk_order() {
    let first = structured_test_summary("Decision alpha was observed.");
    let second = structured_test_summary("Decision beta corrected alpha.");

    let reduced = reduce_validated_lcm_summaries(&[first, second], usize::MAX)
        .expect("deterministic reduction");

    let alpha = reduced.find("Decision alpha").expect("alpha retained");
    let beta = reduced.find("Decision beta").expect("beta retained");
    assert!(alpha < beta);
    assert!(lcm_output_has_required_sections(&reduced));
    assert!(lcm_output_is_grounded(
        &reduced,
        "Decision alpha was observed.\nDecision beta corrected alpha."
    ));
}

#[test]
fn lcm_small_source_summary_is_exact_and_bounded() {
    let messages = vec![make_text_message(
        Role::Assistant,
        "Observed correction: keep rolling as default.",
    )];
    let summary =
        summarize_small_lcm_source(&messages, None, 4_096).expect("small deterministic summary");

    assert!(summary.contains("- [source] Observed correction: keep rolling as default."));
    assert!(summary.len() <= LCM_INLINE_SOURCE_CHARS);
    assert!(lcm_output_has_required_sections(&summary));
    assert!(lcm_output_is_grounded(
        &summary,
        &lcm_safe_source_text(&messages, None)
    ));
}

#[tokio::test]
async fn lcm_critical_prompt_uses_latency_safe_cap() -> Result<()> {
    let systems = Arc::new(std::sync::Mutex::new(Vec::new()));
    let prompts = Arc::new(std::sync::Mutex::new(Vec::new()));
    let provider: Arc<dyn Provider> = Arc::new(PromptCapturingProvider {
        systems,
        prompts: Arc::clone(&prompts),
    });

    generate_lcm_compaction_artifact(
        provider,
        vec![make_text_message(
            Role::User,
            &"observed line\n".repeat(4_000),
        )],
        None,
        Some("latency-cap-route".to_string()),
        LcmJobPriority::Critical,
    )
    .await?;

    let prompts = prompts.lock().expect("prompt lock");
    assert_eq!(prompts.len(), 1);
    assert!(prompts[0].len() <= LCM_CRITICAL_PROMPT_CHARS);
    Ok(())
}

#[test]
fn lcm_prompt_uses_only_the_structured_schema() {
    let opaque_secret = "correct horse battery staple";
    let messages = vec![Message {
        role: Role::Assistant,
        content: vec![
            ContentBlock::ToolUse {
                id: "opaque-call".to_string(),
                name: "credential_helper".to_string(),
                input: serde_json::json!({"password": opaque_secret}),
                thought_signature: None,
            },
            ContentBlock::ToolResult {
                tool_use_id: "opaque-call".to_string(),
                content: opaque_secret.to_string(),
                is_error: Some(false),
            },
        ],
        timestamp: None,
        tool_duration_ms: None,
    }];
    let prompt = build_lcm_compaction_prompt(&messages, None, 8_000);
    assert!(prompt.contains("section schema"));
    assert!(prompt.contains("status=success"));
    assert!(prompt.contains("use conversation_search"));
    assert!(!prompt.contains(opaque_secret));
    assert!(!prompt.contains("Your response should be structured as follows"));
    assert!(
        LCM_REQUIRED_SECTIONS
            .iter()
            .all(|section| LCM_SUMMARY_SYSTEM_PROMPT.contains(section))
    );
}

#[test]
fn lcm_prompt_omits_opaque_secrets_from_plain_text() {
    let labeled_secret = "correct horse battery staple";
    let unlabeled_secret = "q7Vn4Zp9Lx2Kc8Mw5Rt1Hs6Bd3Yf";
    let uppercase_secret = "ABCDEFGH23456789ABCDEFGH23456789";
    let messages = vec![make_text_message(
        Role::User,
        &format!(
            "Session credential: {labeled_secret}\nOpaque value {unlabeled_secret}\n{uppercase_secret}\nKeep this safe line"
        ),
    )];

    let prompt = build_lcm_compaction_prompt(&messages, None, 8_000);

    assert!(!prompt.contains(labeled_secret));
    assert!(!prompt.contains(unlabeled_secret));
    assert!(!prompt.contains(uppercase_secret));
    assert!(prompt.contains("Keep this safe line"));
}

#[tokio::test]
async fn native_compaction_uses_fail_closed_secret_boundary() -> Result<()> {
    let secret = "0123456789abcdef0123456789abcdef";
    let captured_messages = Arc::new(std::sync::Mutex::new(Vec::new()));
    let captured_summary = Arc::new(std::sync::Mutex::new(None));
    let provider: Arc<dyn Provider> = Arc::new(NativeCompactionCapturingProvider {
        messages: Arc::clone(&captured_messages),
        existing_summary: Arc::clone(&captured_summary),
        returned_summary: format!("model returned {secret}"),
    });

    let result = generate_compaction_artifact(
        provider,
        vec![make_text_message(
            Role::User,
            &format!("ordinary source\n{secret}"),
        )],
        Some(Summary {
            text: format!("ordinary prior\n{secret}"),
            openai_encrypted_content: None,
            covers_up_to_turn: 0,
            original_turn_count: 0,
        }),
    )
    .await?;

    assert!(!content_text(&captured_messages.lock().expect("messages lock")[0]).contains(secret));
    assert!(
        !captured_summary
            .lock()
            .expect("summary lock")
            .as_deref()
            .unwrap_or_default()
            .contains(secret)
    );
    assert!(!result.summary_text.contains(secret));
    assert!(result.summary_text.contains(LCM_OMITTED_SOURCE));
    Ok(())
}

#[tokio::test]
async fn lcm_rejects_ungrounded_model_written_secret() {
    let secret = "Authorization: Bearer sk-super-secret-value";
    let provider: Arc<dyn Provider> = Arc::new(StaticSummaryProvider {
        summary: structured_test_summary(secret),
    });
    let result = generate_lcm_compaction_artifact(
        provider,
        vec![make_text_message(Role::User, "Observed work only")],
        None,
        None,
        LcmJobPriority::Background,
    )
    .await;
    assert!(result.is_err());
}

#[tokio::test]
async fn lcm_rejects_grounded_opaque_secret() {
    for secret_source in [
        "q7Vn4Zp9Lx2Kc8Mw5Rt1Hs6Bd3Yf",
        "ABCDEFGH23456789ABCDEFGH23456789",
        "Session credential: correct horse battery staple",
    ] {
        let provider: Arc<dyn Provider> = Arc::new(StaticSummaryProvider {
            summary: structured_test_summary(secret_source),
        });
        let result = generate_lcm_compaction_artifact(
            provider,
            vec![make_text_message(Role::User, secret_source)],
            None,
            None,
            LcmJobPriority::Background,
        )
        .await;

        assert!(
            result.is_err(),
            "secret source must fail closed: {secret_source}"
        );
    }
}

#[tokio::test]
async fn lcm_rejects_completion_claim_absent_from_canonical_source() {
    let provider: Arc<dyn Provider> = Arc::new(StaticSummaryProvider {
        summary: structured_test_summary("All tests pass."),
    });
    let result = generate_lcm_compaction_artifact(
        provider,
        vec![make_text_message(Role::User, "Plan tests for tomorrow")],
        None,
        None,
        LcmJobPriority::Background,
    )
    .await;
    let Err(error) = result else {
        panic!("unsupported completion claim must fail closed")
    };
    assert!(error.to_string().contains("unsupported"));
}

#[tokio::test]
async fn transfer_compaction_uses_explicit_engine_snapshot() -> Result<()> {
    let systems = Arc::new(std::sync::Mutex::new(Vec::new()));
    let prompts = Arc::new(std::sync::Mutex::new(Vec::new()));
    let provider: Arc<dyn Provider> = Arc::new(PromptCapturingProvider {
        systems: Arc::clone(&systems),
        prompts: Arc::clone(&prompts),
    });
    let secret = "tool input {\"api_key\":\"credential-that-must-not-leak\"}";
    let messages = vec![make_text_message(
        Role::User,
        &format!("{} {secret}", "source ".repeat(200)),
    )];
    build_transfer_compaction_state(
        Arc::clone(&provider),
        messages.clone(),
        None,
        crate::config::CompactionEngine::Rolling,
    )
    .await?;
    build_transfer_compaction_state(
        provider,
        messages,
        None,
        crate::config::CompactionEngine::Lcm,
    )
    .await?;

    let captured = systems.lock().unwrap();
    assert_eq!(captured.len(), 2);
    assert_eq!(
        captured[0],
        "You are a helpful assistant that summarizes conversations."
    );
    assert_eq!(captured[1], LCM_SUMMARY_SYSTEM_PROMPT);
    let captured_prompts = prompts.lock().unwrap();
    assert_eq!(captured_prompts.len(), 2);
    for prompt in captured_prompts.iter() {
        assert!(!prompt.contains("credential-that-must-not-leak"));
        assert!(
            prompt.contains("[REDACTED_SECRET]")
                || prompt.contains(crate::message::UNCERTAIN_SECRET_OMISSION),
            "compaction prompt must retain explicit evidence of secret filtering"
        );
    }
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
async fn lcm_scheduler_caps_process_wide_compactor_concurrency() -> Result<()> {
    let active = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let maximum = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let mut tasks = Vec::new();
    for index in 0..12 {
        let provider: Arc<dyn Provider> = Arc::new(ScheduledProvider {
            active: Arc::clone(&active),
            maximum: Arc::clone(&maximum),
        });
        tasks.push(tokio::spawn(async move {
            generate_lcm_compaction_artifact(
                provider,
                vec![make_text_message(
                    Role::User,
                    &format!("scheduled source {index} {}", "x".repeat(1_000)),
                )],
                None,
                None,
                LcmJobPriority::Background,
            )
            .await
        }));
    }
    for task in tasks {
        task.await??;
    }
    let observed = maximum.load(std::sync::atomic::Ordering::SeqCst);
    assert!(observed > 0);
    assert!(observed <= 3, "observed {observed} background compactors");
    assert_eq!(active.load(std::sync::atomic::Ordering::SeqCst), 0);
    Ok(())
}

#[tokio::test]
async fn lcm_scheduler_reserves_capacity_for_critical_work() -> Result<()> {
    let shared = Arc::new(tokio::sync::Semaphore::new(4));
    let background = Arc::new(tokio::sync::Semaphore::new(3));
    let mut admitted_background = Vec::new();
    for _ in 0..4 {
        if admitted_background.len() == 3 {
            break;
        }
        admitted_background.push(
            acquire_lcm_scheduler_from(
                Arc::clone(&shared),
                Arc::clone(&background),
                LcmJobPriority::Background,
                std::time::Duration::from_millis(50),
            )
            .await?,
        );
    }
    assert_eq!(admitted_background.len(), 3);
    let queued_background = acquire_lcm_scheduler_from(
        Arc::clone(&shared),
        Arc::clone(&background),
        LcmJobPriority::Background,
        std::time::Duration::from_millis(20),
    )
    .await;
    match queued_background {
        Err(error) => assert!(error.to_string().contains("queue timed out")),
        Ok(_) => panic!("fourth background job bypassed reserved critical capacity"),
    }

    let critical = acquire_lcm_scheduler_from(
        Arc::clone(&shared),
        Arc::clone(&background),
        LcmJobPriority::Critical,
        std::time::Duration::from_millis(20),
    )
    .await?;
    assert_eq!(shared.available_permits(), 0);
    drop(critical);
    drop(admitted_background);
    assert_eq!(shared.available_permits(), 4);
    assert_eq!(background.available_permits(), 3);
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 8)]
async fn lcm_scheduler_fairness_scorecard_has_bounded_p95_and_no_starvation() -> Result<()> {
    const JOBS_PER_CLASS: usize = 24;
    let shared = Arc::new(tokio::sync::Semaphore::new(4));
    let background = Arc::new(tokio::sync::Semaphore::new(3));
    let mut background_holders = Vec::new();
    for _ in 0..3 {
        background_holders.push(
            acquire_lcm_scheduler_from(
                Arc::clone(&shared),
                Arc::clone(&background),
                LcmJobPriority::Background,
                Duration::from_secs(1),
            )
            .await?,
        );
    }

    let mut jobs = Vec::with_capacity(JOBS_PER_CLASS * 2);
    for priority in [LcmJobPriority::Background, LcmJobPriority::Critical] {
        for sequence in 0..JOBS_PER_CLASS {
            let shared = Arc::clone(&shared);
            let background = Arc::clone(&background);
            jobs.push(tokio::spawn(async move {
                let queued_at = Instant::now();
                let permit = acquire_lcm_scheduler_from(
                    shared,
                    background,
                    priority,
                    Duration::from_secs(2),
                )
                .await?;
                let waited_us = queued_at.elapsed().as_micros();
                tokio::time::sleep(Duration::from_millis(2)).await;
                drop(permit);
                Ok::<_, anyhow::Error>((priority, sequence, waited_us))
            }));
        }
    }

    // Critical work must make progress through the reserved fourth slot even
    // while all three background permits are occupied.
    tokio::time::sleep(Duration::from_millis(20)).await;
    drop(background_holders);

    let mut background_wait_us = Vec::with_capacity(JOBS_PER_CLASS);
    let mut critical_wait_us = Vec::with_capacity(JOBS_PER_CLASS);
    for job in jobs {
        let (priority, _sequence, waited_us) = job.await??;
        match priority {
            LcmJobPriority::Background => background_wait_us.push(waited_us),
            LcmJobPriority::Critical => critical_wait_us.push(waited_us),
        }
    }
    let percentile_us = |samples: &mut Vec<u128>, percentile: usize| {
        samples.sort_unstable();
        samples[(samples.len() * percentile).div_ceil(100) - 1]
    };
    let background_p95_us = percentile_us(&mut background_wait_us, 95);
    let critical_p95_us = percentile_us(&mut critical_wait_us, 95);
    let passed = background_wait_us.len() == JOBS_PER_CLASS
        && critical_wait_us.len() == JOBS_PER_CLASS
        && background_p95_us <= 500_000
        && critical_p95_us <= 500_000
        && shared.available_permits() == 4
        && background.available_permits() == 3;
    let scorecard = serde_json::json!({
        "schema_version": 1,
        "jobs_per_class": JOBS_PER_CLASS,
        "completed": {
            "background": background_wait_us.len(),
            "critical": critical_wait_us.len(),
        },
        "queue_p95_us": {
            "background": background_p95_us,
            "critical": critical_p95_us,
        },
        "thresholds": {
            "queue_p95_us_max": 500_000,
            "starved_jobs_max": 0,
            "shared_permits_restored": 4,
            "background_permits_restored": 3,
        },
        "starved_jobs": 0,
        "passed": passed,
    });
    if let Some(path) = std::env::var_os("JCODE_LCM_SCHEDULER_CERT_OUTPUT") {
        let path = std::path::PathBuf::from(path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(path, serde_json::to_vec_pretty(&scorecard)?)?;
    }
    assert!(passed, "scheduler scorecard failed: {scorecard}");
    Ok(())
}

#[tokio::test(flavor = "multi_thread", worker_threads = 6)]
async fn lcm_scheduler_recovers_capacity_after_stalls_and_cancellation() -> Result<()> {
    let started = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let mut stalled = Vec::new();
    for _ in 0..4 {
        let provider: Arc<dyn Provider> = Arc::new(StallingProvider {
            started: Arc::clone(&started),
        });
        stalled.push(tokio::spawn(generate_lcm_compaction_artifact(
            provider,
            vec![make_text_message(Role::User, &"x".repeat(1_000))],
            None,
            None,
            LcmJobPriority::Critical,
        )));
    }
    tokio::time::timeout(std::time::Duration::from_secs(1), async {
        while started.load(std::sync::atomic::Ordering::SeqCst) < 4 {
            tokio::task::yield_now().await;
        }
    })
    .await?;
    for task in &stalled {
        task.abort();
    }
    for task in stalled {
        match task.await {
            Err(error) => assert!(error.is_cancelled()),
            Ok(_) => panic!("aborted compactor task unexpectedly completed"),
        }
    }

    let provider: Arc<dyn Provider> = Arc::new(MockSummaryProvider);
    tokio::time::timeout(
        std::time::Duration::from_secs(1),
        generate_lcm_compaction_artifact(
            provider,
            vec![make_text_message(Role::User, &"y".repeat(1_000))],
            None,
            None,
            LcmJobPriority::Critical,
        ),
    )
    .await??;

    let provider: Arc<dyn Provider> = Arc::new(StallingProvider {
        started: Arc::new(std::sync::atomic::AtomicUsize::new(0)),
    });
    let stalled_result = generate_lcm_compaction_artifact(
        provider,
        vec![make_text_message(Role::User, &"z".repeat(1_000))],
        None,
        None,
        LcmJobPriority::Critical,
    )
    .await;
    let Err(error) = stalled_result else {
        panic!("stalled provider must time out")
    };
    assert!(error.to_string().contains("timed out"));
    Ok(())
}

#[test]
fn lcm_chunking_does_not_split_parallel_tool_transactions() {
    let calls = Message {
        role: Role::Assistant,
        content: vec![
            ContentBlock::ToolUse {
                id: "call-a".to_string(),
                name: "read".to_string(),
                input: serde_json::json!({"path": "a.rs"}),
                thought_signature: None,
            },
            ContentBlock::ToolUse {
                id: "call-b".to_string(),
                name: "read".to_string(),
                input: serde_json::json!({"path": "b.rs"}),
                thought_signature: None,
            },
        ],
        timestamp: None,
        tool_duration_ms: None,
    };
    let result_a = Message {
        role: Role::User,
        content: vec![ContentBlock::ToolResult {
            tool_use_id: "call-a".to_string(),
            content: "a".repeat(200),
            is_error: None,
        }],
        timestamp: None,
        tool_duration_ms: None,
    };
    let result_b = Message {
        role: Role::User,
        content: vec![ContentBlock::ToolResult {
            tool_use_id: "call-b".to_string(),
            content: "b".repeat(200),
            is_error: Some(true),
        }],
        timestamp: None,
        tool_duration_ms: None,
    };
    let chunks = lcm_message_chunks(
        vec![
            make_text_message(Role::User, "before"),
            calls,
            result_a,
            result_b,
            make_text_message(Role::Assistant, "consumed both results"),
        ],
        100,
    );

    let transaction_chunk = chunks
        .iter()
        .find(|chunk| {
            chunk.iter().any(|message| {
                message.content.iter().any(
                    |block| matches!(block, ContentBlock::ToolUse { id, .. } if id == "call-a"),
                )
            })
        })
        .expect("parallel tool transaction chunk");
    let rendered =
        jcode_compaction_core::build_compaction_conversation_text(transaction_chunk, None);
    assert!(rendered.contains("id=call-a"));
    assert!(rendered.contains("id=call-b"));
    assert!(rendered.contains("tool_use_id=call-a"));
    assert!(rendered.contains("tool_use_id=call-b"));
    assert!(rendered.contains("tool_use_id=call-a status=unknown"));
    assert!(rendered.contains("tool_use_id=call-b status=error"));
    assert!(rendered.contains("consumed both results"));
}

#[test]
fn lcm_chunking_preserves_missing_and_orphan_tool_result_evidence() {
    let missing_call = Message {
        role: Role::Assistant,
        content: vec![ContentBlock::ToolUse {
            id: "missing-call".to_string(),
            name: "write".to_string(),
            input: serde_json::json!({"path": "src/missing.rs"}),
            thought_signature: None,
        }],
        timestamp: None,
        tool_duration_ms: None,
    };
    let repair_context = make_text_message(
        Role::Assistant,
        "The tool result is missing; do not claim the write completed.",
    );
    let orphan_result = Message {
        role: Role::User,
        content: vec![ContentBlock::ToolResult {
            tool_use_id: "orphan-call".to_string(),
            content: "recovered result tail".to_string(),
            is_error: Some(true),
        }],
        timestamp: None,
        tool_duration_ms: None,
    };
    let chunks = lcm_message_chunks(vec![missing_call, repair_context, orphan_result], 1);
    assert!(chunks.iter().any(|chunk| {
        let rendered = build_compaction_conversation_text(chunk, None);
        rendered.contains("missing-call") && rendered.contains("do not claim")
    }));
    let rendered = chunks
        .iter()
        .map(|chunk| build_compaction_conversation_text(chunk, None))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(rendered.contains("orphan-call"));
    assert!(rendered.contains("status=error"));
    assert!(rendered.contains("recovered result tail"));
}

#[tokio::test]
async fn lcm_source_chunks_run_with_bounded_concurrency() -> Result<()> {
    let active = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let maximum = Arc::new(std::sync::atomic::AtomicUsize::new(0));
    let provider: Arc<dyn Provider> = Arc::new(ScheduledProvider {
        active: Arc::clone(&active),
        maximum: Arc::clone(&maximum),
    });
    let messages = (0..6)
        .map(|index| {
            make_text_message(
                Role::User,
                &format!("chunk-{index}: {}", "observed source ".repeat(80)),
            )
        })
        .collect();

    let summary = summarize_lcm_source_with_budget(&provider, messages, None, 2_000, 2_000).await?;

    assert!(lcm_output_has_required_sections(&summary));
    assert_eq!(
        maximum.load(std::sync::atomic::Ordering::SeqCst),
        LCM_CHUNK_CONCURRENCY
    );
    assert_eq!(active.load(std::sync::atomic::Ordering::SeqCst), 0);
    Ok(())
}

const LCM_CERT_TRACE_COUNT: usize = 30;
const LCM_CERT_FACTS_PER_TRACE: usize = 5;
const LCM_CERT_CYCLES: usize = 2;
const LCM_CERT_MIN_RECALL: f64 = 0.95;
const LCM_CERT_MIN_WILSON_LOWER: f64 = 0.95;
const LCM_CERT_MAX_OUTPUT_SOURCE_RATIO: f64 = 0.35;
const LCM_CERT_MAX_P95_US: u128 = 1_000_000;

/// Neutral generator contract for external Hermes: iterate trace `0..30`, then
/// cycle `0..2`, then kinds `DECISION,CONSTRAINT,CORRECTION,PATH,ERROR`. Cycle 0
/// plants `phase56 <kind> trace <TRACE:02> retains value <TRACE:02>`;
/// cycle 1 deliberately does not repeat it, so recall must survive the prior
/// compaction. Use the exact format strings below, UTF-8, LF, and ascending
/// indexes. This is byte-reproducible and scrubbed: no secrets or operator data.
fn lcm_cert_trace(trace: usize, cycle: usize) -> (Vec<String>, Vec<Message>) {
    let kinds = ["decision", "constraint", "correction", "path", "error"];
    let facts = kinds
        .iter()
        .map(|kind| format!("phase56 {kind} trace {trace:02} retains value {trace:02}"))
        .collect::<Vec<_>>();
    let filler = (0..40)
        .map(|index| format!("phase56_trace_{trace:02}_coding_filler_{index:03}"))
        .collect::<Vec<_>>()
        .join(" ");
    let mut messages: Vec<Message> = facts
        .iter()
        .enumerate()
        .flat_map(|(turn, fact)| {
            let planted = if cycle == 0 {
                format!("planted fact: {fact}. ")
            } else {
                String::new()
            };
            [
                make_text_message(
                    Role::User,
                    &format!(
                        "trace {trace:02} cycle {cycle} turn {turn}: {planted}inspect src/module_{trace:02}.rs"
                    ),
                ),
                make_text_message(
                    Role::Assistant,
                    &format!(
                        "Observed cycle {cycle} turn {turn}; the coding task remains pending. Evidence: {} {filler}",
                        "source and test output remain canonical. ".repeat(4),
                    ),
                ),
            ]
        })
        .collect();
    messages.push(make_text_message(
        Role::User,
        "Recall every planted token from this trace; do not claim the task is complete.",
    ));
    messages.push(make_text_message(
        Role::Assistant,
        "Recall is pending compaction; the coding task remains pending.",
    ));
    (facts, messages)
}

fn lcm_cert_active_recall(summary: &str, facts: &[String]) -> usize {
    facts
        .iter()
        .filter(|fact| summary.contains(fact.as_str()))
        .count()
}

fn lcm_cert_percentile(samples: &mut [u128], percentile: usize) -> u128 {
    samples.sort_unstable();
    samples[(samples.len() * percentile).div_ceil(100) - 1]
}

fn lcm_cert_wilson_95(successes: usize, total: usize) -> (f64, f64) {
    let z = 1.959_963_984_540_054_f64;
    let n = total as f64;
    let proportion = successes as f64 / n;
    let denominator = 1.0 + z * z / n;
    let center = (proportion + z * z / (2.0 * n)) / denominator;
    let margin =
        z * ((proportion * (1.0 - proportion) / n + z * z / (4.0 * n * n)).sqrt()) / denominator;
    (center - margin, center + margin)
}
